[COREGEN.VERILOG Component Instantiation.bram1]
text000=" "
text001=" "
text002="// The following must be inserted into your Verilog file for this"
text003="// core to be instantiated. Change the instance name and port connections"
text004="// (in parentheses) to your own signal names."
text005=" "
text006="bram1 YourInstanceName ("
text007="    .addra(addra),"
text008="    .addrb(addrb),"
text009="    .clka(clka),"
text010="    .clkb(clkb),"
text011="    .dina(dina),"
text012="    .doutb(doutb),"
text013="    .wea(wea));"
text014=""
text015=" "
type=template
[COREGEN.VERILOG Component Instantiation.bram2]
text000=" "
text001=" "
text002="// The following must be inserted into your Verilog file for this"
text003="// core to be instantiated. Change the instance name and port connections"
text004="// (in parentheses) to your own signal names."
text005=" "
text006="bram2 YourInstanceName ("
text007="    .addra(addra),"
text008="    .addrb(addrb),"
text009="    .clka(clka),"
text010="    .clkb(clkb),"
text011="    .dina(dina),"
text012="    .doutb(doutb),"
text013="    .wea(wea));"
text014=""
text015=" "
type=template
[COREGEN.VHDL Component Instantiation.bram1]
text000=" "
text001=" "
text002="-- The following code must appear in the VHDL architecture header:"
text003=" "
text004="component bram1"
text005="    port ("
text006="    addra: IN std_logic_VECTOR(12 downto 0);"
text007="    addrb: IN std_logic_VECTOR(12 downto 0);"
text008="    clka: IN std_logic;"
text009="    clkb: IN std_logic;"
text010="    dina: IN std_logic_VECTOR(1 downto 0);"
text011="    doutb: OUT std_logic_VECTOR(1 downto 0);"
text012="    wea: IN std_logic);"
text013="end component;"
text014=""
text015=""
text016=""
text017=" "
text018="-------------------------------------------------------------"
text019=" "
text020="-- The following code must appear in the VHDL architecture body."
text021="-- Substitute your own instance name and net names."
text022=" "
text023="your_instance_name : bram1"
text024="        port map ("
text025="            addra => addra,"
text026="            addrb => addrb,"
text027="            clka => clka,"
text028="            clkb => clkb,"
text029="            dina => dina,"
text030="            doutb => doutb,"
text031="            wea => wea);"
text032=" "
type=template
[COREGEN.VHDL Component Instantiation.bram2]
text000=" "
text001=" "
text002="-- The following code must appear in the VHDL architecture header:"
text003=" "
text004="component bram2"
text005="    port ("
text006="    addra: IN std_logic_VECTOR(12 downto 0);"
text007="    addrb: IN std_logic_VECTOR(12 downto 0);"
text008="    clka: IN std_logic;"
text009="    clkb: IN std_logic;"
text010="    dina: IN std_logic_VECTOR(1 downto 0);"
text011="    doutb: OUT std_logic_VECTOR(1 downto 0);"
text012="    wea: IN std_logic);"
text013="end component;"
text014=""
text015=""
text016=""
text017=" "
text018="-------------------------------------------------------------"
text019=" "
text020="-- The following code must appear in the VHDL architecture body."
text021="-- Substitute your own instance name and net names."
text022=" "
text023="your_instance_name : bram2"
text024="        port map ("
text025="            addra => addra,"
text026="            addrb => addrb,"
text027="            clka => clka,"
text028="            clkb => clkb,"
text029="            dina => dina,"
text030="            doutb => doutb,"
text031="            wea => wea);"
text032=" "
type=template
